"""
SmartForge — report_node
==========================
Final report assembly.  Generates the Three-Section Enterprise Report via
Groq and attaches all metadata to final_output before the graph reaches END.

Three sections (generated by groq_client.generate_groq_narrative)
------------------------------------------------------------------
Section 1  Executive Summary
    Non-technical 2–3 sentence overview addressed to the claimant.
    Generated by Groq; falls back to a rule-based template if Groq fails.

Section 2  Forensic Integrity Report
    ELA / Laplacian / SerpAPI status + trust verdict.
    Generated by Groq; falls back to raw forensic context string.

Section 3  Detailed Estimate
    Line-item cost table for the adjuster.
    ALWAYS rule-based — the LLM must never invent financial numbers.

Confirmed-only filter (Batch 3 fix)
--------------------------------------
Previous versions matched only "confirmed" as a valid verification_status.
This version matches ALL three confirmed statuses:
    "confirmed"
    "gemini_golden_frame_confirmed"   (set by verification_v2)
    "gemini_confirmed"                (set by Gemini Task 4 discovery)

Score normalisation
-------------------
If no confirmed damages remain (all were rejected by Gemini or the FP gate),
the overall_assessment_score is overridden to 100 and inspection_recommendation
is set to "No Repair Required".  A clean vehicle should not be penalised
because YOLO found reflections that Gemini subsequently rejected.

Output persistence
------------------
    /content/final_output.json   — always written
    Drive backup                 — written if DRIVE_MOUNTED is True

State mutations returned
------------------------
    final_output     dict  — enriched with narrative, job_summary, score override
    messages         list  — one entry appended
"""

import json
import os
import shutil
from datetime import datetime, timezone
from typing import Any, Dict, List

from src.config.settings import cfg
from src.models.groq_client import generate_groq_narrative
from src.graph.state import SmartForgeState, log_msg

# Verification statuses that count as "confirmed" for report purposes
_CONFIRMED_STATUSES = {
    "confirmed",
    "gemini_golden_frame_confirmed",
    "gemini_confirmed",
}

# Output paths
_LOCAL_OUTPUT_PATH = "/content/final_output.json"
_DRIVE_OUTPUT_PATH = "/content/drive/MyDrive/SmartForge/final_output.json"
_DRIVE_MOUNTED     = os.path.exists("/content/drive/MyDrive")


def _template_report(d: dict) -> str:
    """Rule-based per-damage fallback when Groq is unavailable."""
    return (
        f"Summary: {d['severity']} {d['type'].lower()} detected at {d['location']}.\n"
        f"Impact: {d['damage_category']} damage affecting vehicle condition and value.\n"
        f"Action: {d.get('repair_type', 'Inspect and repair')}. "
        f"Estimated cost: {d.get('estimated_repair_cost', 'N/A')}."
    )


def report_node(state: SmartForgeState) -> dict:
    """
    LangGraph node: final report assembly — Three-Section Enterprise Report.

    Reads from state
    ----------------
    final_output, damages_output, financial_estimate, fraud_report,
    vehicle_type, vehicle_make_estimate, job_id, started_at,
    retry_count, messages, pipeline_trace

    Returns partial state update
    ----------------------------
    final_output (enriched), messages
    """
    output   = dict(state["final_output"] or {})
    damages  = state["damages_output"]

    print(f"\n🔵 [report] generating narrative for confirmed damages…")
    print(
        f"   GenAI backend: "
        f"{'Groq API (' + cfg.GROQ_MODEL + ')' if cfg.GROQ_ENABLED else 'rule-based template (GROQ_API_KEY not set)'}"
    )

    # ── Filter to confirmed damages only ──────────────────────────────────────
    confirmed_damages: List[Dict[str, Any]] = [
        d for d in damages
        if d.get("verification_status") in _CONFIRMED_STATUSES
        and not d.get("rejected", False)
        and d.get("is_verified") is not False
    ]
    n_confirmed = len(confirmed_damages)
    n_total     = len(damages)
    print(f"   Confirmed: {n_confirmed}/{n_total} detections")

    # ── Per-damage fallback AI reports (for record detail in DB/dashboard) ────
    for i, d in enumerate(damages):
        if "ai_report" not in d:
            damages[i]["ai_report"] = _template_report(d)

    # ── Build vehicle context string for Groq ─────────────────────────────────
    vehicle_context = (
        f"{state.get('vehicle_make_estimate', 'unknown')} "
        f"{state.get('vehicle_type', 'unknown')}"
    ).strip()

    # ── Generate three-section narrative ──────────────────────────────────────
    financial_est  = state.get("financial_estimate") or {}
    fraud_rep      = state.get("fraud_report")       or {}

    narrative_dict = generate_groq_narrative(
        damage_list        = confirmed_damages,
        vehicle_context    = vehicle_context,
        fraud_report       = fraud_rep,
        financial_estimate = financial_est,
    )

    ai_narrative = narrative_dict["full_narrative"]
    print(
        f"   ✅ Three-section narrative generated "
        f"({'Groq API' if cfg.GROQ_ENABLED else 'template'})."
    )

    # ── Score normalisation: no confirmed damages → perfect score ─────────────
    if n_confirmed == 0:
        output["overall_assessment_score"]  = 100
        output["inspection_recommendation"] = "No Repair Required"
        print("   ✅ Score normalised to 100 — no confirmed damages.")

    # ── Enrich final_output with narrative sections ───────────────────────────
    output.update({
        "ai_narrative_summary":   ai_narrative,
        "executive_summary":      narrative_dict.get("executive_summary",  ""),
        "forensic_report":        narrative_dict.get("forensic_report",    ""),
        "detailed_estimate_text": narrative_dict.get("detailed_estimate",  ""),
        "confirmed_damage_count": n_confirmed,
        "financial_estimate":     financial_est,
        "damages":                damages,          # all records preserved for audit
    })

    # ── Job summary ───────────────────────────────────────────────────────────
    completed_at = datetime.now(timezone.utc)
    try:
        started_dt   = datetime.fromisoformat(
            state["started_at"].rstrip("Z")
        ).replace(tzinfo=timezone.utc)
        elapsed_secs = round((completed_at - started_dt).total_seconds(), 1)
    except Exception:
        elapsed_secs = None

    output["job_summary"] = {
        "job_id":          state["job_id"],
        "started_at":      state["started_at"],
        "completed_at":    completed_at.isoformat() + "Z",
        "elapsed_seconds": elapsed_secs,
        "agents_run": [
            "intake", "fraud", "perception", "gemini_agent",
            "false_positive_gate", "health_monitor", "verification_v2",
            "reasoning", "decision", "report",
        ],
        "retry_count":  state["retry_count"],
        "total_messages": len(state["messages"]),
        "status":        "completed",
    }

    output["pipeline_trace"] = {
        **state["pipeline_trace"],
        "report_agent": {
            "timestamp": completed_at.isoformat(),
            "reasoning": (
                f"Batch 3 report. {n_confirmed}/{n_total} confirmed damages. "
                f"Single Groq narrative generated. "
                f"Score {'normalised to 100' if n_confirmed == 0 else 'unchanged from reasoning_node'}."
            ),
            "decision": "Final output assembled.",
            "api_used": f"Groq {cfg.GROQ_MODEL}" if cfg.GROQ_ENABLED else "rule-based template",
        },
    }

    # ── Persist final output ──────────────────────────────────────────────────
    try:
        os.makedirs(os.path.dirname(_LOCAL_OUTPUT_PATH), exist_ok=True)
        with open(_LOCAL_OUTPUT_PATH, "w") as fh:
            json.dump(output, fh, indent=2, default=str)
        print(f"✅ report: final_output saved → {_LOCAL_OUTPUT_PATH}")
    except Exception as exc:
        print(f"   ⚠️  Could not save final_output.json: {exc}")

    if _DRIVE_MOUNTED:
        try:
            os.makedirs(os.path.dirname(_DRIVE_OUTPUT_PATH), exist_ok=True)
            shutil.copy2(_LOCAL_OUTPUT_PATH, _DRIVE_OUTPUT_PATH)
        except Exception:
            pass

    return {
        "final_output": output,
        "messages": [
            log_msg(
                "report_agent",
                f"Report complete. confirmed={n_confirmed}/{n_total}. "
                f"elapsed={elapsed_secs}s.",
            )
        ],
    }
