"""
SmartForge — Groq LLM Client
==============================
Thin wrapper around the Groq Python SDK for fast text generation.
Provides:
  - call_groq(prompt)            → raw string from Groq
  - generate_groq_narrative(…)   → three-section structured report dict

Why Groq instead of a local model?
  Replaces the previous local IBM Granite 4-bit setup which required ~3 min
  install time and 8 GB GPU RAM per Colab session.  Groq inference is
  typically under 1 second on llama-3.3-70b-versatile (free tier).

Usage
-----
    from src.models.groq_client import call_groq, generate_groq_narrative

    text = call_groq("Write a one-sentence summary of: ...")

    report = generate_groq_narrative(
        damage_list       = confirmed_damages,
        vehicle_context   = "sedan-class car",
        fraud_report      = fraud_report_dict,
        financial_estimate = financial_estimate_dict,
    )
    print(report["executive_summary"])
"""

from typing import Any, Dict, List, Optional

from src.config.settings import cfg

# ── Sentinel value for failed Groq calls ─────────────────────────────────────
_GROQ_FAILED = "__FAILED__"


def call_groq(
    prompt: str,
    max_tokens: int = 250,
    temperature: float = 0.2,
) -> str:
    """
    Call the Groq API and return the model's response as a string.

    Returns _GROQ_FAILED ("__FAILED__") on any error so callers can detect
    failure without catching exceptions.

    Parameters
    ----------
    prompt      : str   — user message to send to the model
    max_tokens  : int   — maximum tokens to generate (default 250)
    temperature : float — sampling temperature (default 0.2 for factual output)
    """
    if not cfg.GROQ_ENABLED:
        return _GROQ_FAILED

    try:
        from groq import Groq
        client   = Groq(api_key=cfg.GROQ_API_KEY)
        response = client.chat.completions.create(
            model       = cfg.GROQ_MODEL,
            messages    = [{"role": "user", "content": prompt}],
            max_tokens  = max_tokens,
            temperature = temperature,
        )
        return response.choices[0].message.content.strip()

    except Exception as exc:
        print(f"   ⚠️  Groq API call failed: {exc}")
        return _GROQ_FAILED


def generate_groq_narrative(
    damage_list: List[Dict[str, Any]],
    vehicle_context: str,
    fraud_report: Optional[Dict[str, Any]] = None,
    financial_estimate: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    """
    Generate the Three-Section Enterprise Report via Groq.

    Sections
    --------
    Section 1 — Executive Summary
        Clear, non-technical 2–3 sentence overview for the claimant.
        Generated by Groq (or rule-based fallback when Groq is unavailable).

    Section 2 — Forensic Integrity Report
        ELA / Laplacian / SerpAPI status + overall trust verdict.
        Generated by Groq (or raw forensic data as fallback).

    Section 3 — Detailed Estimate
        Line-item cost table for the adjuster.
        Always rule-based — the LLM must never invent financial numbers.

    Parameters
    ----------
    damage_list        : list of confirmed damage dicts from reasoning_node
    vehicle_context    : human-readable vehicle description e.g. "sedan-class car"
    fraud_report       : optional fraud layer output dict
    financial_estimate : optional financial engine output dict

    Returns
    -------
    dict with keys:
        executive_summary   str
        forensic_report     str
        detailed_estimate   str
        full_narrative      str  (all three sections combined)
    """
    # ── Rule-based fallback (used when Groq is disabled or all calls fail) ────
    fallback: Dict[str, str] = {
        "executive_summary":  (
            f"Vehicle assessed with {len(damage_list)} confirmed damage(s). "
            "Professional repair is recommended."
        ),
        "forensic_report":    "Forensic checks completed. See fraud_report for details.",
        "detailed_estimate":  "See financial_estimate for line-item costs.",
        "full_narrative":     (
            f"Vehicle assessed with {len(damage_list)} confirmed damage(s). "
            "Professional repair is recommended. "
            "See individual records for details."
        ),
    }

    if not damage_list:
        fallback["executive_summary"] = (
            "No confirmed damages found. Vehicle appears undamaged."
        )
        fallback["full_narrative"] = fallback["executive_summary"]
        return fallback

    # ── Build damage summary string shared across prompts ────────────────────
    damage_summary = "\n".join([
        f"  - {d.get('type', '?')} at {d.get('location', '?')} "
        f"(Severity: {d.get('severity_gemini', d.get('severity', '?'))}, "
        f"Action: {d.get('repair_recommendation', d.get('repair_type', '?'))})"
        for d in damage_list
    ])

    # ── Build forensic context string (Section 2) ─────────────────────────────
    if fraud_report:
        fr_trust   = fraud_report.get("trust_score",   "N/A")
        fr_status  = fraud_report.get("status",        "N/A")
        fr_flags   = fraud_report.get("flags",         [])
        checks_run = fraud_report.get("checks_run",    0)
        details    = fraud_report.get("details",       {})
        ela_score  = details.get("ai_generation_check", {}).get("ela_score",          "N/A")
        lap_var    = details.get("ai_generation_check", {}).get("laplacian_variance",  "N/A")
        serp_found = details.get("serpapi_check",      {}).get("found_online",         None)
        ai_method  = details.get("ai_generation_check", {}).get("method",              "N/A")

        forensic_ctx = (
            f"Trust Score: {fr_trust}/100 | Status: {fr_status} | "
            f"Checks run: {checks_run} | ELA score: {ela_score} | "
            f"Laplacian variance: {lap_var} | SerpAPI: {serp_found} | "
            f"AI check method: {ai_method} | "
            f"Active flags: {len(fr_flags)}"
        )
    else:
        forensic_ctx = "Fraud checks bypassed (BYPASS_FRAUD=True) or not run."

    # ── Build financial context string (Section 3) — rule-based, never LLM ───
    if financial_estimate:
        items       = financial_estimate.get("line_items",           [])
        total_usd   = financial_estimate.get("total_repair_usd",     0)
        total_inr   = financial_estimate.get("total_repair_inr_fmt", "N/A")
        total_loss  = financial_estimate.get("total_loss_flag",      False)
        disposition = financial_estimate.get("disposition",          "N/A")

        line_item_str = "\n".join([
            f"  | {it.get('part', '?'):30s} | {it.get('action', '?'):15s} | "
            f"${it.get('cost_usd', 0):>8.2f} | {it.get('cost_inr_fmt', '?'):>12s} |"
            for it in items
        ])
        financial_ctx = (
            f"Line items:\n{line_item_str}\n"
            f"Grand total: ${total_usd:,.2f} USD / {total_inr}\n"
            f"Disposition: {disposition}"
            + ("  ⚠️ TOTAL LOSS" if total_loss else "")
        )
    else:
        financial_ctx = "Financial estimate not available."

    # ── If Groq is disabled return populated fallback with raw context ────────
    if not cfg.GROQ_ENABLED:
        fallback["forensic_report"]   = forensic_ctx
        fallback["detailed_estimate"] = financial_ctx
        fallback["full_narrative"] = (
            f"EXECUTIVE SUMMARY\n{fallback['executive_summary']}\n\n"
            f"FORENSIC INTEGRITY\n{forensic_ctx}\n\n"
            f"DETAILED ESTIMATE\n{financial_ctx}"
        )
        return fallback

    # ── Section 1: Executive Summary ─────────────────────────────────────────
    exec_prompt = (
        f"You are an expert Automotive Insurance Adjuster writing a claim report.\n"
        f"Vehicle: {vehicle_context}\n\n"
        f"Confirmed Damages:\n{damage_summary}\n\n"
        "Write a 2–3 sentence NON-TECHNICAL Executive Summary for the claimant.\n"
        "Explain what was damaged and the recommended course of action.\n"
        "Tone: clear, empathetic, professional. Avoid jargon."
    )
    exec_result    = call_groq(exec_prompt, max_tokens=250)
    exec_summary   = (
        fallback["executive_summary"]
        if exec_result == _GROQ_FAILED
        else exec_result
    )

    # ── Section 2: Forensic Integrity Report ─────────────────────────────────
    forensic_prompt = (
        "You are a Claims Forensic Analyst writing a one-paragraph integrity report.\n"
        f"Forensic data:\n{forensic_ctx}\n\n"
        "Write a concise, factual forensic integrity statement for the legal team.\n"
        "State which checks passed, any flags raised, and the overall trust verdict.\n"
        "Tone: objective, factual, legal-grade. Max 3 sentences."
    )
    forensic_result      = call_groq(forensic_prompt, max_tokens=200)
    forensic_report_text = (
        forensic_ctx
        if forensic_result == _GROQ_FAILED
        else forensic_result
    )

    # ── Section 3: Detailed Estimate — always rule-based ────────────────────
    detailed_estimate_text = financial_ctx

    # ── Combine ───────────────────────────────────────────────────────────────
    full_narrative = (
        f"=== SECTION 1: EXECUTIVE SUMMARY ===\n{exec_summary}\n\n"
        f"=== SECTION 2: FORENSIC INTEGRITY REPORT ===\n{forensic_report_text}\n\n"
        f"=== SECTION 3: DETAILED ESTIMATE ===\n{detailed_estimate_text}"
    )

    return {
        "executive_summary":  exec_summary,
        "forensic_report":    forensic_report_text,
        "detailed_estimate":  detailed_estimate_text,
        "full_narrative":     full_narrative,
    }
